sudo: false

language: ruby

services:
  - docker

script:
  - docker build --build-arg SITE_URL=${SITE_URL} --build-arg SITE_TOKEN=${SITE_TOKEN} --build-arg BUILD_NUMBER=${TRAVIS_BUILD_NUMBER} --build-arg BUILD_DESCRIPTION="TravisCI-automated-build" .
