sudo: false

language: c++

dist: xenial

services:
  - docker

env:
  matrix:
    - COMMAND="docker run -it -v $(pwd):/var/sample arnislielturks/urho3d:10 bash /var/sample/build_windows.sh"
    - COMMAND="docker run -it -v $(pwd):/var/sample arnislielturks/urho3d:10 bash /var/sample/build_linux.sh"
    - COMMAND="./android/script.sh"
script:
  - $(COMMAND)
