version: 2
jobs:
  build_android:
    machine: true
    steps:
    - checkout
    - restore_cache:
        keys:
          - script-{{ checksum "android/script.sh" }}
          - script-
    - run: ./android/script.sh
    - store_artifacts:
        path: ./Urho3D/android/launcher-app/build/outputs/apk/debug/launcher-app-armeabi-v7a-debug.apk
        destination: launcher-app-armeabi-v7a-debug.apk
    - save_cache:
        key: script-{{ checksum "android/script.sh" }}
        paths:
          - Urho3D
  build_windows:
    machine: true
    steps:
      - checkout
      # Build the image
#      - run: docker build -t windows -f Dockerfile-Windows --build-arg SITE_URL=${SITE_URL} --build-arg SITE_TOKEN=${SITE_TOKEN} --build-arg BUILD_NUMBER=${CIRCLE_BUILD_NUM} --build-arg BUILD_DESCRIPTION="CircleCI-automated-build" .
#      - run: id=$(docker create windows)
#      - run: docker cp $id:/code/build.zip windows_build.zip
#      - run: docker rm -v $id
      - run: docker run -it -v $(pwd):/var/sample arnislielturks/urho3d:10 bash /var/sample/build_windows.sh
      - run:
          name: Archiving
          command: |
            mkdir archive
            cp build-windows/bin/ProjectTemplate.exe archive/ProjectTemplate.exe || true
            cp build-windows/bin/ProjectTemplate_d.exe archive/ProjectTemplate_d.exe || true
            cp -r bin/Data archive/Data
            cp -r bin/CoreData archive/CoreData
            rm -rf archive/Data/Saves/Achievements.json
            chmod -R 777 archive
            cd archive
            zip -r "build.zip" *  > /dev/null
      - store_artifacts:
          path: archive/build.zip
          destination: build.zip
  build_linux:
    machine: true
    steps:
    - checkout
    # Build the image
#    - run: docker build -t linux -f Dockerfile-Linux --build-arg SITE_URL=${SITE_URL} --build-arg SITE_TOKEN=${SITE_TOKEN} --build-arg BUILD_NUMBER=${CIRCLE_BUILD_NUM} --build-arg BUILD_DESCRIPTION="CircleCI-automated-build" .
#    - run: id=$(docker create linux)
#    - run: docker cp $id:/code/build.zip linux_build.zip
#    - run: docker rm -v $id
    - run: docker run -it -v $(pwd):/var/sample arnislielturks/urho3d:10 bash /var/sample/build_linux.sh
    - run:
        name: Archiving
        command: |
          mkdir archive
          cp build/bin/ProjectTemplate archive/ProjectTemplate || true
          cp build/bin/ProjectTemplate_d archive/ProjectTemplate_d || true
          cp -r bin/Data archive/Data
          cp -r bin/CoreData archive/CoreData
          cp -r bin/ProjectTemplate.desktop archive/ProjectTemplate.desktop
          rm -rf archive/Data/Saves/Achievements.json
          chmod -R 777 archive
          chmod a+x archive/ProjectTemplate.desktop
          cd archive
          zip -r "build.zip" *  > /dev/null
    - store_artifacts:
        path: archive/build.zip
        destination: build.zip
  artifact_publish:
    machine: true
    steps:
      - run:
workflows:
  version: 2
  build:
    jobs:
    - build_linux
    - build_windows
    - build_android
