version: 2
jobs:
  build_android:
    machine: true
    steps:
    - checkout
    - restore_cache:
        keys:
          - script-{{ checksum "android/script.sh" }}
          - script-
    - run: ./android/script.sh
    - store_artifacts:
        path: ./Urho3D/android/launcher-app/build/outputs/apk/debug/
        # destination: launcher-app-armeabi-v7a-debug.apk
    - save_cache:
        key: script-{{ checksum "android/script.sh" }}
        paths:
          - ./Urho3D
  build_windows:
    machine: true
    steps:
      - checkout
      - run: docker run -it -v $(pwd):/var/sample arnislielturks/urho3d:27-windows bash /var/sample/build_windows.sh
      - run:
          name: Archiving
          command: |
            mkdir archive
            cp build-windows/bin/ProjectTemplate.exe archive/ProjectTemplate.exe || true
            cp build-windows/bin/ProjectTemplate_d.exe archive/ProjectTemplate_d.exe || true
            cp -r bin/Data archive/Data
            cp -r bin/CoreData archive/CoreData
            rm -rf archive/Data/Saves/Achievements.json
            chmod -R 777 archive
            cd archive
            zip -r "build.zip" *  > /dev/null
      - run:
          name: Upload to itch.io
          command: |
            curl -L -o butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default
            unzip butler.zip
            ./butler push archive/ miegamicis/sandbox:windows-64bit
      - store_artifacts:
          path: archive/build.zip
          destination: ProjectTemplate_Windows.zip
  build_linux:
    machine: true
    steps:
    - checkout
    - run: docker run -it -v $(pwd):/var/sample arnislielturks/urho3d:25-linux bash /var/sample/build_linux.sh
    - run:
        name: Archiving
        command: |
          mkdir archive
          cp build/bin/ProjectTemplate archive/ProjectTemplate || true
          cp build/bin/ProjectTemplate_d archive/ProjectTemplate_d || true
          cp -r bin/Data archive/Data
          cp -r bin/CoreData archive/CoreData
          cp -r bin/ProjectTemplate.desktop archive/ProjectTemplate.desktop
          rm -rf archive/Data/Saves/Achievements.json
          chmod -R 777 archive
          chmod a+x archive/ProjectTemplate.desktop
          cd archive
          zip -r "build.zip" *  > /dev/null
    - run:
        name: Upload to itch.io
        command: |
          curl -L -o butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default
          unzip butler.zip
          ./butler push archive/ miegamicis/sandbox:windows-64bit
    - store_artifacts:
        path: archive/build.zip
        destination: ProjectTemplate_Linux.zip
workflows:
  version: 2
  build:
    jobs:
    - build_android
    - build_linux
    - build_windows
    - build_linux_no_scripts
    - build_windows_no_scripts
