name: Build Windows

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Build Linux
      run: docker run -v $(pwd):/var/sample arnislielturks/urho3d:14 bash /var/sample/build_windows.sh
